### ISSUE TITLE
boot counter example in readme counts by 2 on esp32-s3

### ISSUE THREAD

**Issue by pvhoof** [vshymanskyy/Preferences#13]
The example in the readme does not count correctly, it counts by two
if i add "delay(1000);" before the "prefs.putInt("counter", counter);" it counts correctly; is there some timing issue?

**Comment by vshymanskyy** [comment]
This library is not related to ESP32.
ESP32 uses native Preferences

**Comment by Gifford47** [comment]
I'm confused, in the readme you wrote "Provides ESP32-compatible Preferences API for a wider variety of platforms:" ??

**Comment by vshymanskyy** [comment]
Yes, the API is similar, the implementation is platform specific. But this library cannot run on ESP32, as for ESP32 you have the original library included in the Arduino Core
