### ISSUE TITLE
[feature request] Prevent losing perferences on update of filesystem?

### ISSUE THREAD

**Issue by szprytny** [vshymanskyy/Preferences#14]
@vshymanskyy 
Currently on upload of filesystem image (I do it with PlatformIO), I am losing data that was stored via this library. Do you know a way to prevent this? Is there a way for ESP8266 to create custom smaller Partition dedicated just for Preferences?

**Comment by vshymanskyy** [comment]
This is out of scope for this library. Afaik you cannot create partitions on ESP8266 easily
