### ISSUE TITLE
examples/Prefs2Struct /Prefs2Struct.ino printf

### ISSUE THREAD

**Issue by fungreenfox** [vshymanskyy/Preferences#15]
Esp32 has not "printf"
Please make a version from the Prefs2Struct.ino

**Comment by vshymanskyy** [comment]
How comes Esp32 has not "printf".
What do you mean Esp32

**Comment by fungreenfox** [comment]
Noticed warnings when trying to use printf.

If you look at all the 3rd party non Arduino.cc products, they all include a printf() method in their Print class.

This allows doing.

Serial.printf("this is an integer counter: %04d", counter);

So if using say ESP32, ESP8266, chipkit, Teensy, Intel, rp2040, STM32,.... etc. platform/cores you have a printf() method.

Arduino.cc absolutely refuses to add a printf() method to the Print class any of their platform/cores.

**Comment by vshymanskyy** [comment]
But, how this is esp32 - related? Please clarify your request

нд, 26 трав. 2024 р., 20:15 користувач Fungreenfox ***@***.***>
пише:

**Comment by fungreenfox** [comment]
Also https://forum.arduino.cc/t/esp32-where-can-i-find-the-reference-for-serial-printf-the-print-with-the-f-as-a-suffix/1007598

**Comment by fungreenfox** [comment]
It appears that printf is not standard on esp32, but might work with adding extra library.

**Comment by vshymanskyy** [comment]
This Library is not designed to work on ESP32.
ESP32 does support printf, regardless.

нд, 26 трав. 2024 р., 20:32 користувач Fungreenfox ***@***.***>
пише:
