### ISSUE TITLE
Too long names causes problems

### ISSUE THREAD

**Issue by Stipena** [vshymanskyy/Preferences#16]
So I had issue where long naming caused that particular preference not work. In my case it was "doorAcceleration1" and "doorAcceleration2" that not worked for me and returned value of 0. If like example "unsigned int door_acceleration_1 = 50;" then it would return 50. Changed "doorAcceleration1" and "doorAcceleration2" to "dAcc1" and "dAcc2" and it started to work.

```
unsigned int speed_1;
unsigned int door_speed_1;
unsigned int speed_2;
unsigned int door_speed_2;
unsigned int acceleration_1;
unsigned int door_acceleration_1;
unsigned int acceleration_2;
unsigned int door_acceleration_2;
unsigned int open_1;
unsigned int open_2;
unsigned int door_1;
unsigned int middle_2;
unsigned int percentage_1;

void resetDefaults() {
  speed_1 = 250;
  door_speed_1 = 1000;
  speed_2 = 150;
  door_speed_2 = 200;
  acceleration_1 = 10000;
  door_acceleration_1 = 355000;
  acceleration_2 = 250;
  door_acceleration_2 = 10000;
  open_1 = 10000;
  open_2 = 2000;
  door_1 = 5000;
  middle_2 = 1000;
  percentage_1 = 50;

  preferences.putInt("speed1", speed_1);
  preferences.putInt("doorSpeed1", door_speed_1);
  preferences.putInt("speed2", speed_2);
  preferences.putInt("doorSpeed2", door_speed_2);
  preferences.putInt("acceleration1", acceleration_1);
  preferences.putInt("doorAcceleration1", door_acceleration_1);
  preferences.putInt("acceleration2", acceleration_2);
  preferences.putInt("doorAcceleration2", door_acceleration_2);
  preferences.putInt("open1", open_1);
  preferences.putInt("open2", open_2);
  preferences.putInt("door1", door_1);
  preferences.putInt("middle2", middle_2);
  preferences.putInt("percentage1", percentage_1);
}
```

**Comment by Dario503** [comment]
You are correct, from source code in example: [](https://github.com/vshymanskyy/Preferences/blob/main/examples/StartCounter/StartCounter.ino)

 // Get the counter value, if the key does not exist, return a default [value](url) of 0
  // Note: **Key name is limited to 15 chars.**
  unsigned int counter = preferences.getUInt("counter", 0)
  
  also check .h files:
  
    #define DCT_VARIABLE_NAME_SIZE      16

assuming one char is for null termination of string
