### ISSUE TITLE
getType has hardcoded return PT_INVALID

### ISSUE THREAD

**Issue by abdasgup** [vshymanskyy/Preferences#4]
Document (https://espressif-docs.readthedocs-hosted.com/projects/arduino-esp32/en/latest/api/preferences.html) says this method is supposed to check if data exists for the key and return corresponding data type represented by the enum.
But looking into this repo (for ESP8266), it shows the return value is hardcoded to be PT_INVALID. Tested on NodeMCU and it does return so even when I have UChar data saved and can retrieve it using getUChar.

Was the implementation missed while writing it for ESP8266? Can we please have this fixed ASAP?

**Comment by abdasgup** [comment]
Looked at the ESP32 implementation (https://github.com/espressif/arduino-esp32/blob/master/libraries/Preferences/src/Preferences.cpp) and confirmed it's indeed a miss in ESP8266 version.

If original author doesn't get to address it sooner, can someone please create a PR porting the ESP32 implementations equivalent code for this?

**Comment by vshymanskyy** [comment]
No, we can't fix this ASAP.
