### ISSUE TITLE
ESP8266HTTPUpdateServer.h conflicts with preferences

### ISSUE THREAD

**Issue by xhorack** [vshymanskyy/Preferences#7]
Dear sir,
as a first let me say thank you for your graet job!
As a second, unfortunately, when using preferences library with HTTP update server, the update server not working anymore. When you try to upload bin file to the ESP, ESP restarts itself. I have no idea why, may be your code shares same part of flash like update server...
I didn't tested it yet on ESP32 if the result will be the same, may be it's problem of both platform.

Thanks,
Petr

I'm sure Ukraine will win agaist russian evil!!!

**Comment by vshymanskyy** [comment]
Please provide exact steps to reproduce, minimal sketch example with this issue, etc
