### ISSUE TITLE
My preferences is showing me previously stored value even after clearing the preferences...  

### ISSUE THREAD

**Issue by Sudheer474** [vshymanskyy/Preferences#9]
Is anyone have an idea about why preferences keep showing the previously stored value even after running the pref.clear() method for the opened namespace. I'm using preferences library to store a boolean value in esp32 controller. If anyone have experienced this pls share your thoughts, I'll be grateful.
Thanking you.

**Comment by vshymanskyy** [comment]
This Preferences library does not support ESP32. On esp32, you are using the original/native `Preferences` library:
https://github.com/espressif/arduino-esp32/tree/master/libraries/Preferences

So, this question is irrelevant here
